---
- hosts: localhost
  collections:
    - operator_framework.operator_sdk

  tasks:
    - name: Get version of operator-sdk modules are using
      version_info:
      register: version
    - debug:
        var: version
    - name: validate bundle
      bundle_validate:
        file_path: "/Users/shawnhurley/repos/operator-framwork/operator-sdk-ansible-collection/testdata/3scale-operator-bad"
      register: validation
      ignore_errors: true
    - debug:
        var: validation
    - name: validate ok bundle
      bundle_validate:
        file_path: "/Users/shawnhurley/repos/operator-framwork/operator-sdk-ansible-collection/testdata/3scale-operator"
      register: validation_ok
      ignore_errors: true
    - debug:
        var: validation_ok
